name: Prod Rekognition Analysis

on:
  push:
    branches:
      - main

jobs:
  analyze-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Rekognition Analysis (Prod)

        env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  DYNAMODB_TABLE_BETA: ${{ secrets.DYNAMODB_TABLE_BETA }}
  DYNAMODB_TABLE_PROD: ${{ secrets.DYNAMODB_TABLE_PROD }}
